name: Build and publish
on: 
  push:
    tags:
    - "*" # Running this workflow for any tag
  workflow_dispatch:

jobs:
  push-chiaki-build-image:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: 'Install podman'
        run: sudo apt-get install -y podman
      - name: 'Build chiaki-ng build image'
        run: |
          podman build -f chiaki-ng-build-container/Dockerfile -t ghcr.io/streetpea/chiaki-build-switch:${{ github.ref_name }} .
          podman push ghcr.io/streetpea/chiaki-build-switch:${{ github.ref_name }}
          podman tag ghcr.io/streetpea/chiaki-build-switch:${{ github.ref_name }} ghcr.io/streetpea/chiaki-build-switch:latest
          podman push ghcr.io/streetpea/chiaki-build-switch:latest
